In [1]:
import numpy as np

from gradvi.models.basis_matrix import bm_trendfiltering as basemat

In [21]:
n = 1024
degree = 3

H = basemat.trendfiltering_scaled(n, degree)
#Hs, s, m = basemat.center_and_scale_tfbasis(H)
Hinv = basemat.trendfiltering_inverse_scaled(n, degree)
#Hinvs = np.linalg.inv(Hs)

#tibs = np.power(n, degree) / np.math.factorial(degree)

The first column has all equal values.
The first column has all equal values.


In [22]:
HinvH = np.dot(H, Hinv)

In [23]:
Hinvtrue = np.linalg.inv(H)

In [24]:
np.allclose(HinvH, np.eye(n), atol = 1e-6)

True

In [25]:
np.allclose(Hinv, Hinvtrue, atol = 1e-6)

False

In [26]:
idx = np.where(np.abs(Hinv - Hinvtrue) > 1e-9)

In [27]:
H[idx]

array([ 0.03125   , -0.05407376, -0.03490019, ...,  0.31427209,
        0.31653125,  0.32361086])

In [28]:
Hinvtrue[idx]

array([ 3.12487671e-02,  3.12526228e-02,  3.12486743e-02, ...,
       -1.78180667e-09,  1.27173796e-09,  1.29688011e-09])

In [29]:
idx

(array([   0,    0,    0, ..., 1023, 1023, 1023]),
 array([  0,   1,   2, ..., 958, 959, 962]))

In [30]:
Hinvtrue[0, :10]

array([0.03124877, 0.03125262, 0.03124867, 0.03124716, 0.031254  ,
       0.031247  , 0.03125721, 0.0312407 , 0.03125408, 0.03125568])

In [31]:
Hinv[0, :]

array([0.03125, 0.03125, 0.03125, ..., 0.03125, 0.03125, 0.03125])

In [32]:
np.sum(np.square(H[:, 0]))

1.0

In [34]:
np.sum(np.square(H), axis = 0)

array([1., 1., 1., ..., 1., 1., 1.])