In [63]:
import numpy as np

from gradvi.priors import Ash 
from gradvi.priors.normal_means import NormalMeans as NMeans
from gradvi.tests import toy_priors

In [70]:
def get_nm_data():
    np.random.seed(100)
    n  = 100
    y  = np.random.normal(0, 1, size = n)
    scale = 1.2**2
    dj = np.ones(n) * np.square(np.random.normal(1, 2, size = n)) * n
    sj2 = scale / dj
    return n, y, sj2, scale, dj

n, y, sj2, scale, dj = get_nm_data()
priors = toy_priors.get_all()

In [71]:
[x.prior_type for x in priors]

['ash', 'ash_scaled']

In [76]:
prior = priors[0]

nm = NMeans.create(y, prior, sj2, debug = True, scale = scale, d = dj)

eps = 1e-8
scale_eps = scale + eps
sj2_eps = scale_eps / dj
nm_eps = NMeans.create(y, prior, sj2_eps, debug = True, scale = scale_eps, d = dj)
d1 = nm.logML_s2deriv / dj
d2 = (nm_eps.logML - nm.logML) / eps
assert(np.allclose(d1, d2, atol = 1e-4, rtol = 1e-8))
#assert(np.allclose(d1, d2))

In [77]:
nm.logML_s2deriv / dj

array([ 0.00807337,  0.11344045,  0.00137418,  0.54712329,  0.16361322,
       -0.27268621,  0.55074219,  0.02975605,  0.50659251,  0.01884288,
        0.01748241,  0.04717506, -0.15326787,  0.01743168,  0.29112888,
        0.19770588,  0.0020034 ,  0.00561457,  0.00469135,  0.06183636,
        0.00990807,  0.00158252,  0.0758009 ,  0.02288262, -0.11283203,
        0.00913686,  0.00405262,  0.03951476,  0.01074619,  0.10258898,
        0.08055266,  0.01996104,  0.00258949,  0.00382685,  0.01644632,
        0.51088672,  0.00839281,  0.03009164,  0.00593867,  0.01004629,
        0.01065052,  0.32784357, -0.30852269, -0.20133693,  0.00135718,
        0.41122235,  0.59242808,  0.01071877,  0.02212582,  0.5321092 ,
        0.00109045,  0.34505984,  0.00844119,  0.01371656, -0.26783526,
        0.02462857,  0.00162626,  0.18030674,  0.6956686 ,  0.15315501,
        0.03373609, -0.33385955,  0.01635816, -0.29299466,  0.00182466,
        0.00895108,  0.02252793,  0.00403675,  0.00347914,  0.05

In [74]:
d2

array([ 1.14484440e+00,  6.44569509e-02,  5.21341281e-01,  4.81066875e-01,
        4.18365431e-01, -2.87814084e-01,  4.76128226e-01,  4.51296733e-01,
        4.10643985e-01, -2.98151281e-02,  3.15090620e-02,  4.50790960e-02,
       -1.75928327e-01,  2.63702704e-01,  2.68391731e-01,  1.44739820e-01,
        5.75589798e-02,  4.16948076e-01,  9.07487419e-03,  4.92299224e-01,
        9.90183224e-01,  9.05757691e-01, -1.78048021e-02,  2.81931412e-01,
       -1.63247349e-01,  3.46827100e-01,  2.04094608e-01,  7.12907333e-01,
       -1.53276947e-02,  6.11338535e-02, -3.53598928e-02,  7.98231525e-01,
        2.21403251e-01,  2.61994781e-01,  2.17671969e-01,  4.78257434e-01,
        5.53815660e-01,  1.06872378e+00,  7.12704074e-01,  5.92992144e-01,
        7.13539006e-02,  3.05251335e-01, -3.39431727e-01, -2.19859175e-01,
        6.57912258e-01,  1.05429692e+00,  5.91166227e-01, -6.97706337e-03,
        9.81581927e-01,  8.92079521e-01,  5.52905366e-01,  3.52495788e-01,
        3.48869511e-01,  

In [75]:
d2

array([ 1.14484440e+00,  6.44569509e-02,  5.21341281e-01,  4.81066875e-01,
        4.18365431e-01, -2.87814084e-01,  4.76128226e-01,  4.51296733e-01,
        4.10643985e-01, -2.98151281e-02,  3.15090620e-02,  4.50790960e-02,
       -1.75928327e-01,  2.63702704e-01,  2.68391731e-01,  1.44739820e-01,
        5.75589798e-02,  4.16948076e-01,  9.07487419e-03,  4.92299224e-01,
        9.90183224e-01,  9.05757691e-01, -1.78048021e-02,  2.81931412e-01,
       -1.63247349e-01,  3.46827100e-01,  2.04094608e-01,  7.12907333e-01,
       -1.53276947e-02,  6.11338535e-02, -3.53598928e-02,  7.98231525e-01,
        2.21403251e-01,  2.61994781e-01,  2.17671969e-01,  4.78257434e-01,
        5.53815660e-01,  1.06872378e+00,  7.12704074e-01,  5.92992144e-01,
        7.13539006e-02,  3.05251335e-01, -3.39431727e-01, -2.19859175e-01,
        6.57912258e-01,  1.05429692e+00,  5.91166227e-01, -6.97706337e-03,
        9.81581927e-01,  8.92079521e-01,  5.52905366e-01,  3.52495788e-01,
        3.48869511e-01,  

In [43]:
d1

array([-1.00291499e+00,  3.20006276e+01, -5.40249040e-01,  1.95936766e+01,
       -3.80519946e-01,  4.52999146e+00,  9.95938568e-02, -5.28755815e-01,
       -1.88213066e+01,  5.91250585e+00,  1.83115166e+01,  1.32884265e+01,
        1.30737538e+00,  2.55777243e-02,  3.83818746e-01, -4.05319079e+01,
        1.13244985e+00, -4.86553475e-01,  2.45649777e+01, -5.80371219e-01,
       -9.30253268e-01, -9.12448916e-01, -4.64901748e+00, -3.87156784e-02,
       -2.48887187e+01, -2.49820773e-01,  1.87928870e-01, -7.67818377e-01,
        4.71337641e+01, -6.63762343e+01, -1.60772738e+01, -8.15725732e-01,
        1.37746600e-01, -5.22064200e-03,  2.01658181e-01,  1.06595772e+01,
       -6.23180010e-01, -9.91953273e-01, -7.69030354e-01, -6.79383735e-01,
        5.60226653e+00,  4.49867386e-01, -6.95297072e+01,  8.38220801e-01,
       -7.34257258e-01, -1.01083376e+00, -3.73574638e-01,  3.43472375e+01,
       -9.46967585e-01, -8.44380346e-01, -6.58360859e-01,  1.94436436e+00,
       -3.12639963e-01, -

In [13]:
lj, l_bgrad, l_wgrad, l_s2grad = nm.penalty_operator()

In [14]:
lj_eps = nm_eps.penalty_operator(jac = False)

In [15]:
d2 = (lj_eps - lj) / eps

In [16]:
np.max(np.abs(d2 - l_s2grad))

0.1078148112750586

In [18]:
np.sum(d2)

42.84466434967271

In [19]:
np.sum(l_s2grad)

34.912460204039384

In [8]:
s2

1.44

In [9]:
s2 + eps

1.4400000099999999

In [10]:
nm_eps._s2

1.4400000099999999

In [11]:
nm._s2

1.44

In [12]:
nm_eps._d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.

In [13]:
nm._d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.