In [1]:
import numpy as np

In [2]:
n = 10
logLjk = np.abs(np.random.normal(0, 1, n * 2)).reshape(n, 2)

In [3]:
pi1 = 0.4

In [4]:
logm   = np.max(logLjk, axis = 1)

In [5]:
logm

array([1.04880028, 1.36563794, 0.26845441, 1.32219724, 0.71842704,
       0.70012347, 0.21177892, 0.77281443, 0.69020942, 0.6955723 ])

In [6]:
phijk  = np.zeros((n, 2)) 

In [7]:
phijk

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
phijk[:, 0] = (1 - pi1) * np.exp(logLjk[:,  0] - logm)
phijk[:, 1] = pi1 * np.exp(logLjk[:,  1] - logm)

In [16]:
phijk

array([[0.6       , 0.16222641],
       [0.22449927, 0.4       ],
       [0.6       , 0.31341089],
       [0.26150536, 0.4       ],
       [0.6       , 0.31536393],
       [0.6       , 0.35271941],
       [0.6       , 0.34130409],
       [0.31187265, 0.4       ],
       [0.39148638, 0.4       ],
       [0.6       , 0.21891493]])

In [20]:
phijk / np.sum(phijk, axis = 1).reshape(n, 1)

array([[0.78716769, 0.21283231],
       [0.35948684, 0.64051316],
       [0.65687853, 0.34312147],
       [0.39531858, 0.60468142],
       [0.655477  , 0.344523  ],
       [0.62977619, 0.37022381],
       [0.63741357, 0.36258643],
       [0.43810175, 0.56189825],
       [0.49462175, 0.50537825],
       [0.73267683, 0.26732317]])

In [13]:
logm

array([1.04880028, 1.36563794, 0.26845441, 1.32219724, 0.71842704,
       0.70012347, 0.21177892, 0.77281443, 0.69020942, 0.6955723 ])

In [14]:
logLjk[:, 0]

array([1.04880028, 0.38258075, 0.26845441, 0.49172237, 0.71842704,
       0.70012347, 0.21177892, 0.11847971, 0.26323049, 0.6955723 ])

In [5]:
def log_sum_exponent(z):
    """
    log(sum(exp(z))) = M + log(sum(exp(z - M)))
    """
    zmax = np.max(z, axis = 1)
    logsum = np.log(np.sum(np.exp(z-zmax.reshape(-1, 1)), axis = 1)) + zmax
    return logsum


In [6]:
        logLjk = self.logLjk()
        logm   = np.max(logLjk, axis = 1)
        phijk  = np.zeros((self._n, 2)) 
        varjk  = np.zeros((self._n, 2)) 
        mujk   = np.zeros((self._n, 2)) 
        phijk[:, 0] = (1 - self._pi1) * np.exp(logLjk[:,  0] - logm)
        phijk[:, 1] = self._pi1 * np.exp(logLjk[:, 1] - logm)
        phijk /= np.sum(phijk, axis = 1)
        varjk[:, 1] = 1 / ((1 / self._sj2) + (1 / self._sk2[0, 1]))
        mujk[:, 1] = self._y * varjk[:, 1] / self._sj2


array([0.80740477, 0.72165148, 1.21016549, 0.58174327, 1.74220558,
       1.06454834, 1.14691517, 1.09032168, 1.31113255, 0.41907925,
       0.69414361, 1.01158201, 1.74726198, 1.59357111, 0.46807128,
       0.70104541, 0.48992855, 2.09445684, 1.41924327, 1.04599253,
       0.45183554, 0.52925242, 1.15864122, 1.46755001, 1.7193732 ,
       0.73570672, 2.31025742, 0.96644368, 0.59135179, 1.23075588,
       0.80250737, 0.58157398, 1.52757645, 1.65333261, 1.78011321,
       0.46166122, 0.6391105 , 0.09071727, 1.35254192, 0.83021574,
       0.78105816, 0.38115386, 0.77789016, 1.97159593, 0.31610402,
       1.10826015, 0.52854123, 1.3514663 , 1.69573831, 1.00993364,
       1.17689237, 0.48096458, 0.92650227, 1.04708378, 1.4896824 ,
       1.79245755, 1.00325002, 0.73198177, 0.40410464, 1.02203717,
       0.9110565 , 1.06939699, 0.58874757, 0.74399258, 1.37769674,
       0.61767476, 0.24869146, 0.84668953, 0.7594517 , 1.05152422,
       1.28303748, 0.24668118, 1.64980334, 0.71819028, 0.95005

In [7]:
np.log(1)

0.0

In [8]:
logLjk.shape

(100, 2)

In [9]:
logm = np.max(logLjk)

In [10]:
logm

3.127323456536647

In [14]:
xinner = np.exp(logLjk - logm)
xres = np.diff(xinner)

In [15]:
np.exp(logm)

22.81283820224363

In [27]:
xinner[:, 1] - xinner[:, 0]

array([-1.31968985e-01, -1.94611608e-02, -4.91199209e-02,  5.74880382e-02,
       -1.94927766e-02,  1.33159756e-01,  2.59674455e-02, -2.54607203e-01,
       -2.60327841e-02,  5.98874906e-02,  1.59801162e-01,  7.08403442e-02,
        2.07389984e-01,  3.53238829e-02, -6.96476397e-02, -3.25832068e-02,
        3.47929966e-02, -4.00120261e-02, -5.14086055e-02,  8.09723420e-02,
       -8.66737621e-02, -1.48819091e-02,  6.10905430e-02,  6.06221212e-01,
        1.28728212e-02, -2.26529902e-02, -1.40156546e-02,  1.62860563e-01,
        2.39513447e-01,  3.83400628e-02,  6.31357715e-02,  7.56556977e-02,
        1.05505666e-04,  3.75883065e-02,  2.16419977e-02,  4.72604787e-02,
       -2.64414950e-01,  4.86160771e-02, -3.13801691e-01, -1.74723832e-02,
        7.50998071e-02,  8.88869209e-02, -3.01953865e-01, -7.62826747e-02,
       -2.72490243e-03,  8.57235097e-03, -4.83662515e-02, -2.05772698e-02,
        1.35008734e-01,  7.31356436e-03, -7.22292541e-02,  5.52886760e-02,
       -2.84939344e-01,  

In [34]:
h1 = np.diff(xinner)

In [35]:
h2 = np.exp(h1)

In [36]:
h1.shape

(100, 1)

In [37]:
h2.shape

(100, 1)

In [38]:
h12 = np.concatenate((h1, h2), axis = 1)

In [43]:
h12.shape

(100, 2)

In [46]:
np.max(h12, axis = 1)

array([0.93354593, 0.93321639, 1.27588241, 1.01177996, 0.80786871,
       1.17130963, 0.95974154, 1.08112867, 0.8865119 , 0.97326606,
       1.08776801, 0.98029263, 1.16130404, 1.28023918, 0.9666001 ,
       1.00821323, 1.06195903, 1.71365541, 1.04083318, 0.94158811,
       0.97123563, 1.00761734, 0.9788526 , 1.163425  , 1.04426128,
       0.92474962, 0.55786949, 1.00678819, 0.98561152, 1.2051158 ,
       1.13402684, 1.07821359, 0.84909742, 1.50130255, 0.72336821,
       0.99666342, 0.95169269, 0.99968426, 0.87132325, 0.97021515,
       1.03775636, 1.01648703, 1.12986423, 0.77444341, 0.99283106,
       0.93844641, 0.97004791, 0.86192435, 0.7703892 , 0.90288277,
       0.90896428, 0.96035248, 0.96067924, 1.17691027, 1.41493925,
       0.71169047, 0.88835121, 1.00395546, 0.98874452, 0.89432379,
       0.9305594 , 0.88365584, 1.07603696, 0.92821611, 0.93011409,
       1.044161  , 1.01836905, 0.90743779, 0.96093062, 1.06224629,
       0.90124465, 1.03079257, 0.76247721, 1.07771296, 1.14467

In [41]:
h1.shape

(100, 1)

In [28]:
h12.shape

(200, 1)

In [31]:
np.diff(np.exp(logLjk))

array([[-2.64798875e+00],
       [-3.90492774e-01],
       [-9.85602778e-01],
       [ 1.15351102e+00],
       [-3.91127152e-01],
       [ 2.67188185e+00],
       [ 5.21042908e-01],
       [-5.10875348e+00],
       [-5.22353942e-01],
       [ 1.20165660e+00],
       [ 3.20644794e+00],
       [ 1.42142818e+00],
       [ 4.16132885e+00],
       [ 7.08782027e-01],
       [-1.39749629e+00],
       [-6.53789716e-01],
       [ 6.98129668e-01],
       [-8.02850724e-01],
       [-1.03152577e+00],
       [ 1.62472911e+00],
       [-1.73912944e+00],
       [-2.98609011e-01],
       [ 1.22579613e+00],
       [ 1.21639713e+01],
       [ 2.58296188e-01],
       [-4.54537581e-01],
       [-2.81227410e-01],
       [ 3.26783554e+00],
       [ 4.80589370e+00],
       [ 7.69302387e-01],
       [ 1.26683412e+00],
       [ 1.51804939e+00],
       [ 2.11699602e-03],
       [ 7.54218220e-01],
       [ 4.34251780e-01],
       [ 9.48292632e-01],
       [-5.30554822e+00],
       [ 9.75493033e-01],
       [-6.2