## Haar DWT matrix

In [7]:
import numpy as np
def HaarMat(N):
    if N == 1: return np.array([[1]])
    H = 1/np.sqrt(2)*np.concatenate(
        (
            np.kron(HaarMat(N//2),[1,1])
        ,
            np.kron(np.identity(N//2),[1,-1])
        ),axis = 0
        )
    return H

def invHaarMat(N):
    return HaarMat(N).transpose()

In [8]:
np.round(HaarMat(8),2)

array([[ 0.35,  0.35,  0.35,  0.35,  0.35,  0.35,  0.35,  0.35],
       [ 0.35,  0.35,  0.35,  0.35, -0.35, -0.35, -0.35, -0.35],
       [ 0.5 ,  0.5 , -0.5 , -0.5 ,  0.  ,  0.  , -0.  , -0.  ],
       [ 0.  ,  0.  , -0.  , -0.  ,  0.5 ,  0.5 , -0.5 , -0.5 ],
       [ 0.71, -0.71,  0.  , -0.  ,  0.  , -0.  ,  0.  , -0.  ],
       [ 0.  , -0.  ,  0.71, -0.71,  0.  , -0.  ,  0.  , -0.  ],
       [ 0.  , -0.  ,  0.  , -0.  ,  0.71, -0.71,  0.  , -0.  ],
       [ 0.  , -0.  ,  0.  , -0.  ,  0.  , -0.  ,  0.71, -0.71]])

In [9]:
np.round(invHaarMat(8),2)

array([[ 0.35,  0.35,  0.5 ,  0.  ,  0.71,  0.  ,  0.  ,  0.  ],
       [ 0.35,  0.35,  0.5 ,  0.  , -0.71, -0.  , -0.  , -0.  ],
       [ 0.35,  0.35, -0.5 , -0.  ,  0.  ,  0.71,  0.  ,  0.  ],
       [ 0.35,  0.35, -0.5 , -0.  , -0.  , -0.71, -0.  , -0.  ],
       [ 0.35, -0.35,  0.  ,  0.5 ,  0.  ,  0.  ,  0.71,  0.  ],
       [ 0.35, -0.35,  0.  ,  0.5 , -0.  , -0.  , -0.71, -0.  ],
       [ 0.35, -0.35, -0.  , -0.5 ,  0.  ,  0.  ,  0.  ,  0.71],
       [ 0.35, -0.35, -0.  , -0.5 , -0.  , -0.  , -0.  , -0.71]])

### Example

In [4]:
# create a signal x
x = [3, 7, 1, 1, -2, 5, 4, 6]
forwardW = HaarMat(len(x))
# calc wavelet coefficient
wave_coef = np.dot(forwardW,x)

In [5]:
np.round(wave_coef,2)

array([ 8.84, -0.35,  4.  , -3.5 , -2.83,  0.  , -4.95, -1.41])

In [6]:
# transform it back to signal x
invW = invHaarMat(len(x))
np.dot(invW,wave_coef)

array([ 3.,  7.,  1.,  1., -2.,  5.,  4.,  6.])