In [1]:
import numpy as np
from gradvi.models import basis_matrix as gvbm
np.set_printoptions(precision=3)

In [2]:
n = 8

In [3]:
def Xdotv(X, v, degree):
    X3v1 = np.zeros_like(v)
    v0 = v[:degree]
    v1 = v[degree:]
    X3v1[degree:] = np.cumsum(v1)
    for k in range(degree):
        X3v1 = np.cumsum(X3v1)
    if degree == 0:
        res = X3v1
    elif degree == 1:
        res = v[0] + X3v1
    else:
        X0v0 = np.dot(X[:, :degree], v0)
        res = X0v0 + X3v1
    return res

In [4]:
gvbm.trendfiltering_scaled(n, 0)

array([[ 0.354, -0.935, -0.612, -0.456, -0.354, -0.274, -0.204, -0.134],
       [ 0.354,  0.134, -0.612, -0.456, -0.354, -0.274, -0.204, -0.134],
       [ 0.354,  0.134,  0.204, -0.456, -0.354, -0.274, -0.204, -0.134],
       [ 0.354,  0.134,  0.204,  0.274, -0.354, -0.274, -0.204, -0.134],
       [ 0.354,  0.134,  0.204,  0.274,  0.354, -0.274, -0.204, -0.134],
       [ 0.354,  0.134,  0.204,  0.274,  0.354,  0.456, -0.204, -0.134],
       [ 0.354,  0.134,  0.204,  0.274,  0.354,  0.456,  0.612, -0.134],
       [ 0.354,  0.134,  0.204,  0.274,  0.354,  0.456,  0.612,  0.935]])

In [5]:
np.sum(np.square(gvbm.trendfiltering_scaled(n, 0)), axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
gvbm.trendfiltering_scaled(n, 1)

array([[ 0.354, -0.54 , -0.438, -0.362, -0.299, -0.243, -0.191, -0.134],
       [ 0.354, -0.386, -0.438, -0.362, -0.299, -0.243, -0.191, -0.134],
       [ 0.354, -0.231, -0.271, -0.362, -0.299, -0.243, -0.191, -0.134],
       [ 0.354, -0.077, -0.104, -0.169, -0.299, -0.243, -0.191, -0.134],
       [ 0.354,  0.077,  0.063,  0.024, -0.06 , -0.243, -0.191, -0.134],
       [ 0.354,  0.231,  0.23 ,  0.217,  0.179,  0.081, -0.191, -0.134],
       [ 0.354,  0.386,  0.397,  0.41 ,  0.418,  0.406,  0.318, -0.134],
       [ 0.354,  0.54 ,  0.563,  0.603,  0.657,  0.73 ,  0.826,  0.935]])

In [7]:
gvbm.trendfiltering_scaled(n, 2)

array([[ 0.354, -0.54 , -0.342, -0.296, -0.255, -0.216, -0.177, -0.134],
       [ 0.354, -0.386, -0.342, -0.296, -0.255, -0.216, -0.177, -0.134],
       [ 0.354, -0.231, -0.293, -0.296, -0.255, -0.216, -0.177, -0.134],
       [ 0.354, -0.077, -0.195, -0.229, -0.255, -0.216, -0.177, -0.134],
       [ 0.354,  0.077, -0.049, -0.093, -0.153, -0.216, -0.177, -0.134],
       [ 0.354,  0.231,  0.146,  0.11 ,  0.051, -0.043, -0.177, -0.134],
       [ 0.354,  0.386,  0.39 ,  0.381,  0.357,  0.302,  0.177, -0.134],
       [ 0.354,  0.54 ,  0.683,  0.72 ,  0.765,  0.821,  0.884,  0.935]])

In [8]:
gvbm.trendfiltering_scaled(n, 3)

array([[ 0.354, -0.54 , -0.342, -0.26 , -0.229, -0.199, -0.168, -0.134],
       [ 0.354, -0.386, -0.342, -0.26 , -0.229, -0.199, -0.168, -0.134],
       [ 0.354, -0.231, -0.293, -0.26 , -0.229, -0.199, -0.168, -0.134],
       [ 0.354, -0.077, -0.195, -0.231, -0.229, -0.199, -0.168, -0.134],
       [ 0.354,  0.077, -0.049, -0.141, -0.177, -0.199, -0.168, -0.134],
       [ 0.354,  0.231,  0.146,  0.037, -0.02 , -0.093, -0.168, -0.134],
       [ 0.354,  0.386,  0.39 ,  0.335,  0.295,  0.225,  0.101, -0.134],
       [ 0.354,  0.54 ,  0.683,  0.781,  0.819,  0.862,  0.906,  0.935]])

In [9]:
gvbm.trendfiltering_scaled(n, 4)

array([[ 0.354, -0.54 , -0.342, -0.26 , -0.213, -0.188, -0.162, -0.134],
       [ 0.354, -0.386, -0.342, -0.26 , -0.213, -0.188, -0.162, -0.134],
       [ 0.354, -0.231, -0.293, -0.26 , -0.213, -0.188, -0.162, -0.134],
       [ 0.354, -0.077, -0.195, -0.231, -0.213, -0.188, -0.162, -0.134],
       [ 0.354,  0.077, -0.049, -0.141, -0.182, -0.188, -0.162, -0.134],
       [ 0.354,  0.231,  0.146,  0.037, -0.061, -0.116, -0.162, -0.134],
       [ 0.354,  0.386,  0.39 ,  0.335,  0.243,  0.17 ,  0.054, -0.134],
       [ 0.354,  0.54 ,  0.683,  0.781,  0.85 ,  0.884,  0.917,  0.935]])

In [10]:
b = np.random.normal(0, 1, size = n)

In [11]:
degree = 0
H = gvbm.trendfiltering(n, degree)
Hs, fscale, floc = gvbm.center_and_scale_tfbasis(H)
np.dot(Hs, b)

array([-1.204, -0.37 , -1.322, -1.   ,  0.09 , -0.174,  0.658,  0.066])

In [12]:
fscale

array([2.828, 0.935, 1.225, 1.369, 1.414, 1.369, 1.225, 0.935])

In [13]:
np.sum(np.square(H / fscale - floc), axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.dot(H, b)

array([-1.151, -0.371, -1.536, -1.096,  0.446,  0.084,  1.104,  0.549])

In [15]:
Xdotv(H, b, degree)

array([-1.151, -0.371, -1.536, -1.096,  0.446,  0.084,  1.104,  0.549])

In [16]:
np.dot(Hs, b)

array([-1.204, -0.37 , -1.322, -1.   ,  0.09 , -0.174,  0.658,  0.066])

In [17]:
Hb = Xdotv(H, b / fscale, degree)
Hb - np.dot(floc, b)

array([-1.204, -0.37 , -1.322, -1.   ,  0.09 , -0.174,  0.658,  0.066])

In [18]:
def Xdotv_scaled(Hk, b, degree, fscale, floc):
    Hkb = Xdotv(Hk, b / fscale, degree)
    Hksb = Hkb - np.dot(b, floc)
    return Hksb

for k in range(5):
    Hk = gvbm.trendfiltering(n, k)
    Hks, fscale, floc = gvbm.center_and_scale_tfbasis(Hk)
    success = np.allclose(np.dot(Hks, b), Xdotv_scaled(Hk, b, k, fscale, floc))
    print(k, success)

0 True
1 True
2 True
3 True
4 True


In [19]:
n = 4096
degree = 5
H = gvbm.trendfiltering(n, degree)
b = np.random.normal(0, 1, size = n)
Hs, fscale, floc = gvbm.center_and_scale_tfbasis(H)

In [20]:
np.allclose(np.dot(Hs, b), Xdotv_scaled(H, b, degree, fscale, floc))

True

In [21]:
%%timeit
np.dot(Hs, b)

7.07 ms ± 723 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
%%timeit
Xdotv_scaled(H, b, degree, fscale, floc)

246 µs ± 1.69 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
