In [1]:
import numpy as np
from gradvi.models import basis_matrix as gvbm

def get_dj(X):
    return np.sum(np.square(X), axis = 0)

def pascal_row(n, degree):
    row = np.ones(n)
    for i in range(degree):
        row = np.cumsum(row)
    return row

def get_dj_fast(n, degree):
    col = pascal_row(n, degree)
    col2 = np.square(col)
    dj = np.zeros(n)
    dj[degree:] = np.cumsum(col2)[:n - degree][::-1]
    for i in range(degree):
        dj[i] = np.sum(np.square(pascal_row(n - i, i)))
    return dj

## Degree 0

In [11]:
n = 10
degree = 0
H = gvbm.trendfiltering(n, degree)
get_dj(H)

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [12]:
get_dj_fast(n, degree)

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

## Degree 1

In [13]:
degree = 1
H = gvbm.trendfiltering(n, degree)
get_dj(H)

array([ 10., 285., 204., 140.,  91.,  55.,  30.,  14.,   5.,   1.])

In [14]:
get_dj_fast(n, degree)

array([ 10., 285., 204., 140.,  91.,  55.,  30.,  14.,   5.,   1.])

## Degree 2

In [15]:
degree = 2
H = gvbm.trendfiltering(n, degree)
get_dj(H)

array([1.000e+01, 2.850e+02, 2.892e+03, 1.596e+03, 8.120e+02, 3.710e+02,
       1.460e+02, 4.600e+01, 1.000e+01, 1.000e+00])

In [16]:
get_dj_fast(n, degree)

array([1.000e+01, 2.850e+02, 2.892e+03, 1.596e+03, 8.120e+02, 3.710e+02,
       1.460e+02, 4.600e+01, 1.000e+01, 1.000e+00])

## Degree 3

In [19]:
degree = 3
H = gvbm.trendfiltering(n, degree)
get_dj(H)

array([1.0000e+01, 2.8500e+02, 2.8920e+03, 1.1934e+04, 4.8780e+03,
       1.7420e+03, 5.1700e+02, 1.1700e+02, 1.7000e+01, 1.0000e+00])

In [20]:
get_dj_fast(n, degree)

array([1.0000e+01, 2.8500e+02, 2.8920e+03, 1.1934e+04, 4.8780e+03,
       1.7420e+03, 5.1700e+02, 1.1700e+02, 1.7000e+01, 1.0000e+00])