In [1]:
import numpy as np
from gradvi.models import basis_matrix as gvbm
np.set_printoptions(precision=3)

In [2]:
n = 8

In [3]:
def Xdotv(X, v, degree):
    X3v1 = np.zeros_like(v)
    v0 = v[:degree]
    v1 = v[degree:]
    X3v1[degree:] = np.cumsum(v1)
    for k in range(degree):
        X3v1 = np.cumsum(X3v1)
    if degree == 0:
        res = X3v1
    elif degree == 1:
        res = v[0] + X3v1
    else:
        X0v0 = np.dot(X[:, :degree], v0)
        res = X0v0 + X3v1
    return res

def XTdotv(X, v, degree):
    vrev = v[::-1]
    X3v1 = np.cumsum(vrev)
    for k in range(degree):
        X3v1 = np.cumsum(X3v1)
    res = X3v1[::-1]
    ## degree 0 do not need any change
    if degree == 1:
        res[0] = np.sum(v)
    else:
        res[:degree] = np.dot(X[:, :degree].T, v)
    return res

In [4]:
gvbm.trendfiltering_scaled(n, 0).T

array([[ 0.354,  0.354,  0.354,  0.354,  0.354,  0.354,  0.354,  0.354],
       [-0.935,  0.134,  0.134,  0.134,  0.134,  0.134,  0.134,  0.134],
       [-0.612, -0.612,  0.204,  0.204,  0.204,  0.204,  0.204,  0.204],
       [-0.456, -0.456, -0.456,  0.274,  0.274,  0.274,  0.274,  0.274],
       [-0.354, -0.354, -0.354, -0.354,  0.354,  0.354,  0.354,  0.354],
       [-0.274, -0.274, -0.274, -0.274, -0.274,  0.456,  0.456,  0.456],
       [-0.204, -0.204, -0.204, -0.204, -0.204, -0.204,  0.612,  0.612],
       [-0.134, -0.134, -0.134, -0.134, -0.134, -0.134, -0.134,  0.935]])

In [5]:
gvbm.trendfiltering_inverse_scaled(n, 0)

array([[ 0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125,  0.125],
       [-0.935,  0.935,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   , -1.225,  1.225,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   , -1.369,  1.369,  0.   ,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   , -1.414,  1.414,  0.   ,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   , -1.369,  1.369,  0.   ,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.225,  1.225,  0.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.935,  0.935]])

In [6]:
gvbm.trendfiltering_scaled(n, 1).T

array([[ 0.354,  0.354,  0.354,  0.354,  0.354,  0.354,  0.354,  0.354],
       [-0.54 , -0.386, -0.231, -0.077,  0.077,  0.231,  0.386,  0.54 ],
       [-0.438, -0.438, -0.271, -0.104,  0.063,  0.23 ,  0.397,  0.563],
       [-0.362, -0.362, -0.362, -0.169,  0.024,  0.217,  0.41 ,  0.603],
       [-0.299, -0.299, -0.299, -0.299, -0.06 ,  0.179,  0.418,  0.657],
       [-0.243, -0.243, -0.243, -0.243, -0.243,  0.081,  0.406,  0.73 ],
       [-0.191, -0.191, -0.191, -0.191, -0.191, -0.191,  0.318,  0.826],
       [-0.134, -0.134, -0.134, -0.134, -0.134, -0.134, -0.134,  0.935]])

In [7]:
gvbm.trendfiltering_scaled(n, 2).T

array([[ 0.354,  0.354,  0.354,  0.354,  0.354,  0.354,  0.354,  0.354],
       [-0.54 , -0.386, -0.231, -0.077,  0.077,  0.231,  0.386,  0.54 ],
       [-0.342, -0.342, -0.293, -0.195, -0.049,  0.146,  0.39 ,  0.683],
       [-0.296, -0.296, -0.296, -0.229, -0.093,  0.11 ,  0.381,  0.72 ],
       [-0.255, -0.255, -0.255, -0.255, -0.153,  0.051,  0.357,  0.765],
       [-0.216, -0.216, -0.216, -0.216, -0.216, -0.043,  0.302,  0.821],
       [-0.177, -0.177, -0.177, -0.177, -0.177, -0.177,  0.177,  0.884],
       [-0.134, -0.134, -0.134, -0.134, -0.134, -0.134, -0.134,  0.935]])

In [8]:
gvbm.trendfiltering_scaled(n, 3).T

array([[ 0.354,  0.354,  0.354,  0.354,  0.354,  0.354,  0.354,  0.354],
       [-0.54 , -0.386, -0.231, -0.077,  0.077,  0.231,  0.386,  0.54 ],
       [-0.342, -0.342, -0.293, -0.195, -0.049,  0.146,  0.39 ,  0.683],
       [-0.26 , -0.26 , -0.26 , -0.231, -0.141,  0.037,  0.335,  0.781],
       [-0.229, -0.229, -0.229, -0.229, -0.177, -0.02 ,  0.295,  0.819],
       [-0.199, -0.199, -0.199, -0.199, -0.199, -0.093,  0.225,  0.862],
       [-0.168, -0.168, -0.168, -0.168, -0.168, -0.168,  0.101,  0.906],
       [-0.134, -0.134, -0.134, -0.134, -0.134, -0.134, -0.134,  0.935]])

In [9]:
gvbm.trendfiltering_scaled(n, 4).T

array([[ 0.354,  0.354,  0.354,  0.354,  0.354,  0.354,  0.354,  0.354],
       [-0.54 , -0.386, -0.231, -0.077,  0.077,  0.231,  0.386,  0.54 ],
       [-0.342, -0.342, -0.293, -0.195, -0.049,  0.146,  0.39 ,  0.683],
       [-0.26 , -0.26 , -0.26 , -0.231, -0.141,  0.037,  0.335,  0.781],
       [-0.213, -0.213, -0.213, -0.213, -0.182, -0.061,  0.243,  0.85 ],
       [-0.188, -0.188, -0.188, -0.188, -0.188, -0.116,  0.17 ,  0.884],
       [-0.162, -0.162, -0.162, -0.162, -0.162, -0.162,  0.054,  0.917],
       [-0.134, -0.134, -0.134, -0.134, -0.134, -0.134, -0.134,  0.935]])

In [10]:
b = np.random.normal(0, 1, size = n)

In [11]:
degree = 0
H = gvbm.trendfiltering(n, degree)
Hs, fscale, floc = gvbm.center_and_scale_tfbasis(H)

In [12]:
np.sum(np.square(Hs), axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.dot(H.T, b)

array([1.925, 1.862, 2.625, 1.727, 2.072, 2.589, 1.507, 1.125])

In [14]:
XTdotv(H, b, degree)

array([1.925, 1.862, 2.625, 1.727, 2.072, 2.589, 1.507, 1.125])

In [15]:
np.dot(Hs.T, b)

array([0.681, 0.19 , 0.964, 0.383, 0.785, 1.364, 0.837, 0.946])

In [16]:
HTb = XTdotv(H, b, degree)
HTb / fscale - floc * np.sum(b)

array([0.681, 0.19 , 0.964, 0.383, 0.785, 1.364, 0.837, 0.946])

In [17]:
def Xdotv_scaled(H, b, degree, fscale, floc):
    Hb = Xdotv(H, b / fscale, degree)
    Hsb = Hb - np.dot(b, floc)
    return Hsb

def XTdotv_scaled(H, b, degree, fscale, floc):
    HTb = XTdotv(H, b, degree)
    HsTb = (HTb / fscale) - (floc * np.sum(b))
    return HsTb

for k in range(5):
    Hk = gvbm.trendfiltering(n, k)
    Hks, fscale, floc = gvbm.center_and_scale_tfbasis(Hk)
    success = np.allclose(np.dot(Hks.T, b), XTdotv_scaled(Hk, b, k, fscale, floc))
    print(k, success)

0 True
1 True
2 True
3 True
4 True


In [18]:
n = 4096
degree = 5
H = gvbm.trendfiltering(n, degree)
b = np.random.normal(0, 1, size = n)
Hs, fscale, floc = gvbm.center_and_scale_tfbasis(H)

In [19]:
np.allclose(np.dot(Hs.T, b), XTdotv_scaled(H, b, degree, fscale, floc))

True

In [20]:
%%timeit
np.dot(Hs.T, b)

7.06 ms ± 55.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
%%timeit
XTdotv_scaled(H, b, degree, fscale, floc)

386 µs ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
