In [1]:
import numpy as np
import collections

import matplotlib.pyplot as plt
from pymir import mpl_stylesheet
from pymir import mpl_utils
mpl_stylesheet.banskt_presentation(splinecolor = 'black', dpi = 72)

from gradvi.tests import toy_data
from gradvi.tests import toy_priors
from gradvi.inference import LinearRegression
from gradvi.models import basis_matrix as gvbm
from gradvi.models.basis_matrix.bm_trendfiltering import center_and_scale_tfbasis

In [2]:
n = 10
k = 0
H = gvbm.trendfiltering(n, k)
b = np.random.normal(0, 1, size = n)
H

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [3]:
Hscale, fscale, floc = center_and_scale_tfbasis(H)

In [4]:
np.testing.assert_almost_equal(np.dot(H, b), 
                               np.cumsum(b))

np.testing.assert_almost_equal(np.dot(H.T, b), 
                               np.cumsum(b[::-1])[::-1])

np.testing.assert_almost_equal(np.dot(Hscale, b), 
                               np.cumsum(b / fscale) - np.dot(floc, b))

np.testing.assert_almost_equal(np.dot(Hscale.T, b),
                               np.cumsum(b[::-1])[::-1] / fscale - np.einsum('i, j -> i', floc, b))

In [5]:
dj = np.sum(np.square(H / fscale - floc), axis = 0)

print(dj)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
n = 10
k = 0
H = gvbm.trendfiltering(n, k)
b = np.random.normal(0, 1, size = n)
H

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
Hscale, fscale, floc = center_and_scale_tfbasis(H)

In [8]:
dj = np.sum(np.square(Hscale), axis = 0)

print(dj)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
np.dot(Hscale, b)

array([ 2.83910881,  5.57127149,  5.0094954 ,  2.5647466 ,  0.21815573,
       -1.40037471, -0.77797276,  0.13652809,  0.49244342,  1.40776459])

In [24]:
np.cumsum(b) / np.cumsum(fscale) - np.dot(floc, b)

array([2.83910881, 3.09896558, 2.5277304 , 1.73373423, 1.20698927,
       0.95405901, 1.07543221, 1.19536451, 1.2303748 , 1.28779009])

In [15]:
np.tile(floc.reshape(-1, 1), n)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [3.        , 3.        , 3.        , 3.        , 3.        ,
        3.        , 3.        , 3.        , 3.        , 3.        ],
       [2.        , 2.        , 2.        , 2.        , 2.        ,
        2.        , 2.        , 2.        , 2.        , 2.        ],
       [1.52752523, 1.52752523, 1.52752523, 1.52752523, 1.52752523,
        1.52752523, 1.52752523, 1.52752523, 1.52752523, 1.52752523],
       [1.22474487, 1.22474487, 1.22474487, 1.22474487, 1.22474487,
        1.22474487, 1.22474487, 1.22474487, 1.22474487, 1.22474487],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.81649658, 0.81649658, 0.81649658, 0.81649658, 0.81649658,
        0.81649658, 0.81649658, 0.81649658, 0.81649658, 0.81649658],
       [0.65465367, 0.65465367, 0.6546536

In [26]:
np.einsum('i, j -> i', floc, b)

array([0.        , 0.78848393, 0.52565595, 0.40147637, 0.32189722,
       0.26282798, 0.21459814, 0.1720613 , 0.13141399, 0.08760933])

In [11]:
b

array([ 0.69520561, -1.20415328,  0.32640923,  0.91015634,  1.26365569,
       -0.6215948 ,  1.36248083, -0.54291606, -0.53776682, -0.2155187 ])

In [12]:
for i in range(3):
    bsum = np.dot(gvbm.trendfiltering(n, i), b)
    print(i, bsum)

0 [ 0.69520561 -0.50894767 -0.18253844  0.7276179   1.99127359  1.36967878
  2.73215962  2.18924356  1.65147674  1.43595804]
1 [ 0.69520561 -0.50894767 -1.38669171 -1.35427942 -0.05821144  0.61626174
  2.65321575  4.14725371  5.10352484  5.84427728]
2 [ 0.69520561 -0.50894767 -1.38669171 -1.02787019  1.8311726   6.56884183
 14.54761836 25.22458611 38.06197828 52.84427615]


In [13]:
## Degree 0
np.cumsum(b)

array([ 0.69520561, -0.50894767, -0.18253844,  0.7276179 ,  1.99127359,
        1.36967878,  2.73215962,  2.18924356,  1.65147674,  1.43595804])

In [21]:
## Degree 1
np.cumsum(np.cumsum(b) - b[0]) + b[0]

array([ 0.69520561, -0.50894767, -1.38669171, -1.35427942, -0.05821144,
        0.61626174,  2.65321575,  4.14725371,  5.10352484,  5.84427728])

In [70]:
## Degree 2

brev1 = np.zeros(n)
brev1[2:] = np.cumsum(b)[1:-1] + b[2:] - b[0] - b[1]
brev1[1] = b[1]
brev0 = np.cumsum(brev1)
brev0[0] = b[0]
np.cumsum(brev0)

array([ 0.69520561, -0.50894767, -1.38669171, -1.02787019,  1.8311726 ,
        6.56884183, 14.54761836, 25.22458611, 38.06197828, 52.84427615])

In [25]:
bsum2 = np.dot(gvbm.trendfiltering(n, 2), b)
bsum2

array([ 0.69520561, -0.50894767, -1.38669171, -1.02787019,  1.8311726 ,
        6.56884183, 14.54761836, 25.22458611, 38.06197828, 52.84427615])

In [65]:
np.diff(bsum2)

array([-1.20415328, -0.87774404,  0.35882153,  2.85904278,  4.73766924,
        7.97877652, 10.67696775, 12.83739216, 14.78229787])

In [68]:
np.cumsum(brev0)

array([ 0.69520561, -0.50894767, -1.38669171, -1.02787019,  1.8311726 ,
        6.56884183, 14.54761836, 25.22458611, 38.06197828, 52.84427615])

In [130]:
bsum = np.zeros(n)
bsum[1:] = np.cumsum(np.cumsum(b[1:]))
print(bsum + b[0])

[-0.33191529 -0.37926541 -1.29734722 -3.05590546 -3.5751052  -3.59311624
 -2.00503981 -0.49337193  0.86527681  1.80360788]


In [147]:
np.cumsum(np.cumsum(np.cumsum(b[2:]))) + b[0] + b[1] + b[1] + b[2]

array([ -2.16807891,  -4.75001874,  -7.80380819, -10.82825857,
       -12.2172824 , -12.04728824, -10.47129523,  -7.90962104])

In [137]:
bsum = np.zeros(n)
bsum[2:] = np.cumsum(np.cumsum(b[2:]))
print(bsum)

[ 0.          0.         -0.8707317  -2.58193982 -3.05378945 -3.02445038
 -1.38902383  0.16999416  1.57599301  2.5616742 ]


In [110]:
bsum = np.cumsum(b)
bsum

array([-0.33191529, -0.37926541, -1.2499971 , -2.09047353, -0.85111503,
       -0.34992633,  1.25616114,  1.17975259,  1.02673345,  0.60641578])

In [116]:
np.cumsum(bsum - bsum[0])[1:] + bsum[0]

array([-0.37926541, -1.29734722, -3.05590546, -3.5751052 , -3.59311624,
       -2.00503981, -0.49337193,  0.86527681,  1.80360788])

In [148]:
b = np.arange(n) + 1

In [160]:
bsum = np.dot(gvbm.trendfiltering(n, 2), b)
bsum

array([  1.,   3.,   8.,  20.,  44.,  86., 153., 253., 395., 589.])

In [164]:
np.dot(gvbm.trendfiltering(n, 1), b)

array([  1.,   3.,   8.,  17.,  31.,  51.,  78., 113., 157., 211.])

In [198]:
brev = np.zeros(n)
brev[0] = 1
brev[1:] = np.diff(bsum)
np.diff(brev)

array([ 1.,  3.,  7., 12., 18., 25., 33., 42., 52.])

In [199]:
print(brev)

[  1.   2.   5.  12.  24.  42.  67. 100. 142. 194.]


In [203]:
brev1 = np.zeros(n)
brev1[1:] = (np.cumsum(b) + b - 2)[:-1]
brev1[1] = b[1]
brev2 = np.cumsum(brev1)
brev2[0] = b[0]
print(brev2)

[  1.   2.   5.  12.  24.  42.  67. 100. 142. 194.]


In [206]:
np.cumsum(b) + b - 2

array([ 0,  3,  7, 12, 18, 25, 33, 42, 52, 63])

In [204]:
brev1

array([ 0.,  2.,  3.,  7., 12., 18., 25., 33., 42., 52.])

In [205]:
brev2

array([  1.,   2.,   5.,  12.,  24.,  42.,  67., 100., 142., 194.])

In [202]:
np.cumsum(brev2)

array([  1.,   3.,   8.,  20.,  44.,  86., 153., 253., 395., 589.])

In [211]:
7 * b[0] + 7 * b[1] + 5 * b[2] + 2 * b[3]

44

In [41]:
H + floc

array([[ 1.        ,  1.5666989 ,  1.31982404,  1.12815215,  0.9696899 ,
         0.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  2.5666989 ,  1.31982404,  1.12815215,  0.9696899 ,
         0.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  3.5666989 ,  2.31982404,  1.12815215,  0.9696899 ,
         0.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  4.5666989 ,  3.31982404,  2.12815215,  0.9696899 ,
         0.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  5.5666989 ,  4.31982404,  3.12815215,  1.9696899 ,
         0.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  6.5666989 ,  5.31982404,  4.12815215,  2.9696899 ,
         1.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  7.5666989 ,  6.31982404,  5.12815215,  3.9696899 ,
         2.83205029,  1.70710678,  0.58834841

In [43]:
H + np.tile(floc.reshape(-1, 1), n).T

array([[ 1.        ,  1.5666989 ,  1.31982404,  1.12815215,  0.9696899 ,
         0.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  2.5666989 ,  1.31982404,  1.12815215,  0.9696899 ,
         0.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  3.5666989 ,  2.31982404,  1.12815215,  0.9696899 ,
         0.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  4.5666989 ,  3.31982404,  2.12815215,  0.9696899 ,
         0.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  5.5666989 ,  4.31982404,  3.12815215,  1.9696899 ,
         0.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  6.5666989 ,  5.31982404,  4.12815215,  2.9696899 ,
         1.83205029,  0.70710678,  0.58834841,  0.46852129,  0.33333333],
       [ 1.        ,  7.5666989 ,  6.31982404,  5.12815215,  3.9696899 ,
         2.83205029,  1.70710678,  0.58834841

In [65]:
Hscaleinv = np.linalg.inv(Hscale)
#M = np.dot(Hscaleinv, H)
Am = np.tile(fscale.reshape(-1, 1), n).T
Bm = np.tile(floc.reshape(-1, 1), n).T
#M =  np.dot(Hscaleinv, Am * (Hscale + Bm))
M = Am * (np.identity(n) + Bm * Hscaleinv)
bscale = np.dot(M, b) 
np.dot(Hscale, bscale)

array([-16.6217838 ,  -6.95097411,  -5.122682  ,  -5.69586799,
        -3.37512236,   3.67305916,   6.83249005,  10.93280462,
        14.91511988,  19.65506656])

In [66]:
np.dot(Hscaleinv, Am * (Hscale + Bm))

array([[ 1.00000000e+00,  4.50000000e+00,  3.60000000e+00,
         2.80000000e+00,  2.10000000e+00,  1.50000000e+00,
         1.00000000e+00,  6.00000000e-01,  3.00000000e-01,
         1.00000000e-01],
       [ 5.26196226e-17,  2.87228132e+00, -3.97202130e-16,
        -5.73254315e-18,  3.14178376e-17,  7.44735385e-17,
        -4.73403150e-17, -1.69154169e-16, -7.51265686e-18,
         1.24011722e-17],
       [-7.89263244e-16, -2.38215898e-15,  2.72763634e+00,
         8.45459246e-17, -4.58458461e-16, -3.04696273e-16,
        -1.85652596e-16, -2.50225390e-17, -6.47473243e-17,
        -2.83901688e-17],
       [ 4.47895349e-16,  3.13751306e-15,  9.13260868e-16,
         2.48193473e+00,  9.05648589e-16,  4.57753240e-16,
         5.53318887e-16,  2.87934834e-16,  6.07563056e-17,
         1.96821506e-17],
       [ 2.93157775e-16, -8.66961733e-16, -2.71941089e-16,
         3.23079555e-16,  2.16564078e+00, -2.63235996e-16,
        -1.12304561e-16, -4.78790818e-17,  3.43245525e-17,
        -3.

In [62]:
Am * (Hscale + Bm)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 2., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 3., 2., 1., 0., 0., 0., 0., 0., 0.],
       [1., 4., 3., 2., 1., 0., 0., 0., 0., 0.],
       [1., 5., 4., 3., 2., 1., 0., 0., 0., 0.],
       [1., 6., 5., 4., 3., 2., 1., 0., 0., 0.],
       [1., 7., 6., 5., 4., 3., 2., 1., 0., 0.],
       [1., 8., 7., 6., 5., 4., 3., 2., 1., 0.],
       [1., 9., 8., 7., 6., 5., 4., 3., 2., 1.]])