In [1]:
import numpy as np
from gradvi.models import basis_matrix as gvbm

In [2]:
n = 4096

In [3]:
def sum_consecutive(arr, m, n):
    idx = np.array((np.arange(n - m), np.arange(m, n))).T.ravel()
    idx = np.append(idx, n - m)
    arrsum = np.add.reduceat(arr, idx)[::2]
    return arrsum

In [4]:
gvbm.trendfiltering(n, 0)

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 1., 0., 0.],
       [1., 1., 1., ..., 1., 1., 0.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [5]:
gvbm.trendfiltering(n, 1)

array([[1.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [1.000e+00, 2.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [1.000e+00, 4.093e+03, 4.092e+03, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [1.000e+00, 4.094e+03, 4.093e+03, ..., 2.000e+00, 1.000e+00,
        0.000e+00],
       [1.000e+00, 4.095e+03, 4.094e+03, ..., 3.000e+00, 2.000e+00,
        1.000e+00]])

In [6]:
gvbm.trendfiltering(n, 2)

array([[1.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.000000e+00, 1.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.000000e+00, 2.000000e+00, 1.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       ...,
       [1.000000e+00, 4.093000e+03, 8.374278e+06, ..., 1.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.000000e+00, 4.094000e+03, 8.378371e+06, ..., 3.000000e+00,
        1.000000e+00, 0.000000e+00],
       [1.000000e+00, 4.095000e+03, 8.382465e+06, ..., 6.000000e+00,
        3.000000e+00, 1.000000e+00]])

In [7]:
gvbm.trendfiltering(n, 3)

array([[1.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.000000e+00, 1.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.000000e+00, 2.000000e+00, 1.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       ...,
       [1.000000e+00, 4.093000e+03, 8.374278e+06, ..., 1.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.000000e+00, 4.094000e+03, 8.378371e+06, ..., 4.000000e+00,
        1.000000e+00, 0.000000e+00],
       [1.000000e+00, 4.095000e+03, 8.382465e+06, ..., 1.000000e+01,
        4.000000e+00, 1.000000e+00]])

In [8]:
gvbm.trendfiltering(n, 4)

array([[1.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.000000e+00, 1.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.000000e+00, 2.000000e+00, 1.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 0.000000e+00],
       ...,
       [1.000000e+00, 4.093000e+03, 8.374278e+06, ..., 1.000000e+00,
        0.000000e+00, 0.000000e+00],
       [1.000000e+00, 4.094000e+03, 8.378371e+06, ..., 5.000000e+00,
        1.000000e+00, 0.000000e+00],
       [1.000000e+00, 4.095000e+03, 8.382465e+06, ..., 1.500000e+01,
        5.000000e+00, 1.000000e+00]])

In [9]:
b = np.random.normal(0, 1, size = n)

In [10]:
degree = 5
H = gvbm.trendfiltering(n, degree)
np.dot(H, b)

array([ 1.29302605e+00,  1.48049917e+00, -1.02177151e-01, ...,
        8.46197740e+16,  8.47302525e+16,  8.48408461e+16])

In [11]:
H0 = H[:degree, :degree]
b0 = b[:degree]
H0

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 2., 1., 0., 0.],
       [1., 3., 3., 1., 0.],
       [1., 4., 6., 4., 1.]])

In [12]:
H1 = H[:degree, degree:]
b1 = b[degree:]
H1

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
H2 = H[degree:, :degree]
H2

array([[1.00000000e+00, 5.00000000e+00, 1.00000000e+01, 1.00000000e+01,
        5.00000000e+00],
       [1.00000000e+00, 6.00000000e+00, 1.50000000e+01, 2.00000000e+01,
        1.50000000e+01],
       [1.00000000e+00, 7.00000000e+00, 2.10000000e+01, 3.50000000e+01,
        3.50000000e+01],
       ...,
       [1.00000000e+00, 4.09300000e+03, 8.37427800e+06, 1.14197238e+10,
        1.16766676e+13],
       [1.00000000e+00, 4.09400000e+03, 8.37837100e+06, 1.14280980e+10,
        1.16880873e+13],
       [1.00000000e+00, 4.09500000e+03, 8.38246500e+06, 1.14364764e+10,
        1.16995154e+13]])

In [14]:
H3 = H[degree:, degree:]
H3

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.10000000e+01, 6.00000000e+00, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [9.54917872e+15, 9.53751347e+15, 9.52585961e+15, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [9.56085539e+15, 9.54917872e+15, 9.53751347e+15, ...,
        6.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [9.57254348e+15, 9.56085539e+15, 9.54917872e+15, ...,
        2.10000000e+01, 6.00000000e+00, 1.00000000e+00]])

In [15]:
H3b1 = np.zeros(n)
H3b1[degree:] = np.cumsum(b1)
for k in range(degree):
    H3b1 = np.cumsum(H3b1)
H3b1

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
       8.46333094e+16, 8.47438012e+16, 8.48544080e+16])

In [16]:
np.dot(H[:, :degree], b0) + H3b1

array([ 1.29302605e+00,  1.48049917e+00, -1.02177151e-01, ...,
        8.46197740e+16,  8.47302525e+16,  8.48408461e+16])

In [17]:
np.dot(H[:, :degree], b0)

array([ 1.29302605e+00,  1.48049917e+00, -1.02177151e-01, ...,
       -1.35354782e+13, -1.35487188e+13, -1.35619691e+13])

In [18]:
%%timeit

def sum_two_consecutive(x):
    return x[1:] + x[:-1]

def pascal_nextrow(prow, n):
    pnext = np.ones_like(prow)
    pnext[1:] = prow[1:] + prow[:-1]
    return pnext

Hb0 = np.zeros(n)
Hb0[:degree] = np.dot(H0, b0)
pascal_row   = H0[-1, :-1]
for i in range(degree, n):
    Hb0[i] = Hb0[i - 1] + np.dot(pascal_row, b0[1:])
    pascal_row = pascal_nextrow(pascal_row, degree - 1)

24.6 ms ± 272 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
%%timeit

np.dot(H[:, :degree], b0)

129 µs ± 270 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [30]:
def Xdotv(X, v, degree):
    X3v1 = np.zeros_like(v)
    v0 = v[:degree]
    v1 = v[degree:]
    X3v1[degree:] = np.cumsum(v1)
    for k in range(degree):
        X3v1 = np.cumsum(X3v1)
    if degree == 0:
        res = X3v1
    elif degree == 1:
        res = v[0] + X3v1
    else:
        X0v0 = np.dot(X[:, :degree], v0)
        res = X0v0 + X3v1
    return res

for k in range(10):
    Hk = gvbm.trendfiltering(n, k)
    success = np.allclose(np.dot(Hk, b), Xdotv(Hk, b, k))
    print(k, success)

0 True
1 True
2 True
3 True
4 True
5 True
6 True
7 True
8 True
9 True


In [31]:
degree = 2
H = gvbm.trendfiltering(n, degree)

In [32]:
%%timeit

np.dot(H, b)

3.79 ms ± 130 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
%%timeit

Xdotv(H, b, degree)

178 µs ± 1.05 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [28]:
np.dot(H[:, :2], b[:2]).shape

(4096,)