In [1]:
import numpy as np
from gradvi.models import basis_matrix as gvbm

In [30]:
n = 4096

In [31]:
def sum_consecutive(arr, m, n):
    idx = np.array((np.arange(n - m), np.arange(m, n))).T.ravel()
    idx = np.append(idx, n - m)
    arrsum = np.add.reduceat(arr, idx)[::2]
    return arrsum

In [32]:
gvbm.trendfiltering(n, 0).T

array([[1., 1., 1., ..., 1., 1., 1.],
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 1., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [33]:
gvbm.trendfiltering(n, 1).T

array([[1.000e+00, 1.000e+00, 1.000e+00, ..., 1.000e+00, 1.000e+00,
        1.000e+00],
       [0.000e+00, 1.000e+00, 2.000e+00, ..., 4.093e+03, 4.094e+03,
        4.095e+03],
       [0.000e+00, 0.000e+00, 1.000e+00, ..., 4.092e+03, 4.093e+03,
        4.094e+03],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e+00, 2.000e+00,
        3.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 1.000e+00,
        2.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        1.000e+00]])

In [34]:
gvbm.trendfiltering(n, 2).T

array([[1.000000e+00, 1.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 1.000000e+00],
       [0.000000e+00, 1.000000e+00, 2.000000e+00, ..., 4.093000e+03,
        4.094000e+03, 4.095000e+03],
       [0.000000e+00, 0.000000e+00, 1.000000e+00, ..., 8.374278e+06,
        8.378371e+06, 8.382465e+06],
       ...,
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 1.000000e+00,
        3.000000e+00, 6.000000e+00],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        1.000000e+00, 3.000000e+00],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 1.000000e+00]])

In [35]:
gvbm.trendfiltering(n, 3).T

array([[1.000000e+00, 1.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 1.000000e+00],
       [0.000000e+00, 1.000000e+00, 2.000000e+00, ..., 4.093000e+03,
        4.094000e+03, 4.095000e+03],
       [0.000000e+00, 0.000000e+00, 1.000000e+00, ..., 8.374278e+06,
        8.378371e+06, 8.382465e+06],
       ...,
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 1.000000e+00,
        4.000000e+00, 1.000000e+01],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        1.000000e+00, 4.000000e+00],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 1.000000e+00]])

In [36]:
gvbm.trendfiltering(n, 4).T

array([[1.000000e+00, 1.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 1.000000e+00],
       [0.000000e+00, 1.000000e+00, 2.000000e+00, ..., 4.093000e+03,
        4.094000e+03, 4.095000e+03],
       [0.000000e+00, 0.000000e+00, 1.000000e+00, ..., 8.374278e+06,
        8.378371e+06, 8.382465e+06],
       ...,
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 1.000000e+00,
        5.000000e+00, 1.500000e+01],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        1.000000e+00, 5.000000e+00],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 0.000000e+00,
        0.000000e+00, 1.000000e+00]])

In [37]:
b = np.random.normal(0, 1, size = n)

In [38]:
degree = 0
H = gvbm.trendfiltering(n, degree)
print(np.dot(H.T, b))
print(np.cumsum(b[::-1])[::-1])

[-4.85754901 -2.9519978  -1.90829663 ...  0.48676727 -1.58321435
 -0.4639602 ]
[-4.85754901 -2.9519978  -1.90829663 ...  0.48676727 -1.58321435
 -0.4639602 ]


In [39]:
degree = 3
H = gvbm.trendfiltering(n, degree)
np.dot(H.T, b)

array([-4.85754901e+00,  2.28060270e+04,  3.18803843e+07, ...,
       -7.04663701e+00, -2.97509497e+00, -4.63960204e-01])

In [40]:
brev = b[::-1]
np.cumsum(np.cumsum(np.cumsum(np.cumsum(brev))))[::-1]

array([ 1.48450020e+10,  1.48130760e+10,  1.47811728e+10, ...,
       -7.04663701e+00, -2.97509497e+00, -4.63960204e-01])

In [41]:
np.dot(H[:, :degree].T, b)

array([-4.85754901e+00,  2.28060270e+04,  3.18803843e+07])

In [42]:
def XTdotv(X, v, degree):
    vrev = v[::-1]
    X3v1 = np.cumsum(vrev)
    for k in range(degree):
        X3v1 = np.cumsum(X3v1)
    res = X3v1[::-1]
    ## degree 0 do not need any change
    if degree == 1:
        res[0] = np.sum(v)
    else:
        res[:degree] = np.dot(X[:, :degree].T, v)
    return res

In [43]:
for k in range(10):
    Hk = gvbm.trendfiltering(n, k)
    success = np.allclose(np.dot(Hk.T, b), XTdotv(Hk, b, k))
    print(k, success)

0 True
1 True
2 True
3 True
4 True
5 True
6 True
7 True
8 True
9 True


In [44]:
degree = 5
H = gvbm.trendfiltering(n, degree)

In [45]:
%%timeit

np.dot(H.T, b)

4.14 ms ± 55.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [46]:
%%timeit

XTdotv(H, b, degree)

344 µs ± 24.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
